name: uni_selected_button
description: Group of buttons where only one button can be selected at a time.
version: 1.0.0
repository: https://github.com/huynguyennovem/uni_selected_button
issue_tracker: https://github.com/huynguyennovem/uni_selected_button/issues

environment:
  sdk: '3.6.0-134.0.dev'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
